### PR TITLE
Action repairs and template migration

### PR DESCRIPTION
**Pull request by jason-edstrom**
- migrated pieces from official template to help with code quality and packaging
- fixed action run

### CODE REVIEW

**Comment by jason-edstrom** [comment]
@zteater, I can remove eslint if you prefer.  CodeFactor is most likely failing due to the `eslintrc.json`.  The github actions template uses ncc to compile everything.

**Comment by jason-edstrom** [comment]
Ugh.  Finally got it nailed down.

**Comment by zteater** [comment]
@jason-edstrom  this looks good, the only thing I'm unclear about is the files in `dist/`. It seems like we would be maintaining `settings.xml` in both `src/` and `dist/`? NPM is definitely not my strong suit, but I am under the impression dist/ is used when running `npm publish` to update a module in npm.

**Comment by jason-edstrom** [comment]
I'm learning how some of this works as well, so no worries. :) When you run `npm run package` locally, it compiles all the needed code into a monolithic index.js and copies the settings.xml file from `src` to `dist`.  I'll do a test run with dist removed to make sure that it is unnecessary.

**Comment by zteater** [comment]
@jason-edstrom  ah makes sense, I deleted both and ran `npm run package` and both were recreated in `dist` without changes necessary, so looks they're up to date.

**Comment by jason-edstrom** [comment]
Woot! I just found this doc reference calling it out.

https://help.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github

**Pull request merged**
